# -*- coding: utf-8 -*-
"""plotting_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uyi88Zf8aRfRIPqBIVAZndUivVC7Ey3o
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/content/fuel_econ.csv')
print(data)

display(data)

# The histogram displays the distribution of CO2 emissions/discharge for the cars in the dataset.
# The distribution of CO2 emissions is right skewed since the mean is greater than the median.
# The number of vehicles with higher CO2 emissions is low.
# The number of vehicles with lower CO2 emissions is high.

mean_co2 = data['co2'].mean()
median_co2 = data['co2'].median()
plt.figure(figsize=(10, 8))
plt.hist(data['co2'], edgecolor="black", color="grey")
plt.xlabel('CO2 Emission')  # Amount of C02 released
plt.ylabel('Number of Vehicles') # Count of cars that fall into each CO2 emission range.
plt.title('Distribution of CO2 Emissions')
plt.axvline(mean_co2, color='y', linestyle='dashed', linewidth=2, label=f'Mean = {mean_co2:.2f}')
plt.axvline(median_co2, color='g', linestyle='dashed', linewidth=2, label=f'Median = {median_co2:.2f}')
print(f"Mean for distribution of CO2 Emission: {mean_co2}")   # Prints the mean value
print(f"Median for distribution of CO2 Emission: {median_co2}") # Prints the meadian value
plt.show()

num_data = data.select_dtypes(include=np.number) # Select only the columns with numerical data from my dataset.
print(num_data)

# This correlation heatmap shows the relationship between all the variables in the dataset.
# The correlation heatmap shows strong negative correlations between CO2 emission and various enomical factors that influence fuel such as city, Ucity, highway and UHighway
# Hence, less co2 discharged.
# It also shows a strong positive between co2 emissions and displ. The cars with larger displ. discharge a high level of co2 due to taking in more fuel.

plt.figure(figsize=(12, 10)) # Adjust the width and height for the numbers to show clearly
sns.heatmap(num_data.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap of CO2')
plt.show()